version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/deployment
hooks:
  AfterInstall:
    - location: install_app_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user